// src/lib/components/common/googlesheetsdata.jsx
import { PageBodySideMenu } from '@/components/common';
import { v4 as uuidv4 } from 'uuid';

export default function GoogleSheetsData({ name, values }) {
  let categories = [];
  getCategories();
  categories.forEach(setEntryCount);

  function getCategories() {
    let categoryList = [];
    let i;
    for (i = 1; i < values.length; i++) {
      let category = values[i][0];
      if (category !== '') {
        let categoryObject = {
          row: i,
          category: values[i][0],
          entries: 0,
        };

        categories.push(categoryObject);
      }
    }
  }

  function setEntryCount(item, index) {
    if (categories.length < 2) {
      categories[0].entries = values.length - 2;
    } else {
      let i;
      for (i = 0; i < categories.length - 1; i++) {
        categories[i].entries = categories[i + 1].row - categories[i].row - 1;
      }
      categories[i].entries = values.length - categories[i].row - 1;
    }
  }

  const updated = values[0][3];
  const combinedAuthorTitle = values[0][2] === 'Not Used';
  function buildCategoryList(category) {
    return category;
  }
  const categoryList = categories.map(buildCategoryList);

  function buildListValues(category, index) {
    const rowNumber = category.row;
    const entries = category.entries;
    const lastEntry = rowNumber + entries;
    function createListValue(entry, index) {
      return index > rowNumber && index < lastEntry + 1;
    }
    const listValue = values.filter(createListValue);
    return listValue;
  }
  const listValues = categoryList.map(buildListValues);

  function buildLis(listValue) {
    if (combinedAuthorTitle) {
      function createLi1(listValue) {
        return (
          <li key={uuidv4()}>
            <p>{listValue[1]}</p>
          </li>
        );
      }
      const li = listValue.map(createLi1);
      return li;
    } else {
      function createLi2(listValue, index) {
        if (name === 'RecentDonors') {
          let imo = '';
          if (listValue[2]) {
            imo = ` (${listValue[2]})`;
          }

          return (
            <li key={uuidv4()}>
              <p>
                {listValue[1]}
                {imo}
              </p>
            </li>
          );
        }

        return (
          <li key={uuidv4()}>
            <p>
              {listValue[1]},{' '}
              <span>
                <i>{listValue[2]}</i>
              </span>
            </p>
          </li>
        );
      }
      const li = listValue.map(createLi2);
      return li;
    }
  }
  const lis = listValues.map(buildLis);

  //then, build the lists
  function buildList(list, index) {
    return (
      <>
        {categoryList.length > 1 || name === 'YouthSection' ? (
          <h4>{list.category}</h4>
        ) : null}
        <ul key={uuidv4()} className='gsheets-data'>
          {lis[index]}
        </ul>
        <br />
      </>
    );
  }
  const lists = categoryList.map(buildList);

  return (
    <>
      <div className='updated'>
        <i>{updated}</i>
      </div>

      {name === 'Books' && (
        <h3>Rental or New at the Library</h3>
      )}
      {name === 'RecentDonors' && (
        <h2>Thanks to those who have donated to the Library recently.</h2>
      )}
      {lists}
      {name === 'Books' && (
        <section id='books-footer'>
          <b>KAREN MARTORELLI</b><br />
          <i>Acquisitions Chair</i>
        </section>
      )}
    </>
  );
}

// src/lib/components/common/googlesheetsdata.svelte
<script>
  export let name;
  export let values;
  let categories = [];
  getCategories();
  categories.forEach(setEntryCount);

  function getCategories() {
    let categoryList = [];
    let i;
    for (i = 1; i < values.length; i++) {
      let category = values[i][0];
      if (category !== '') {
        let categoryObject = {
          row: i,
          category: values[i][0],
          entries: 0,
        };

        categories.push(categoryObject);
      }
    }
  }

  function setEntryCount(item, index) {
    if (categories.length < 2) {
      categories[0].entries = values.length - 2;
    } else {
      let i;
      for (i = 0; i < categories.length - 1; i++) {
        categories[i].entries = categories[i + 1].row - categories[i].row - 1;
      }
      categories[i].entries = values.length - categories[i].row - 1;
    }
  }

  const updated = values[0][3];
  const combinedAuthorTitle = values[0][2] === 'Not Used';

  const categoryList = categories.map(buildCategoryList);
  function buildCategoryList(category) {
    return category;
  }

  const listValues = categoryList.map(buildListValues);
  function buildListValues(category, index) {
    const rowNumber = category.row;
    const entries = category.entries;
    const lastEntry = rowNumber + entries;
    const listValue = values.filter(createListValue);
    function createListValue(entry, index) {
      return index > rowNumber && index < lastEntry + 1;
    }
    return listValue;
  }
</script>

  
  <div id='updated'>
    <i>{updated}</i>
  </div>


{#if (name === 'Books')}
  <h3>Rental or New at the Library</h3>
{/if}
{#if (name === 'RecentDonors')}
  <h2>Thanks to those who have donated to the Library recently.</h2>
{/if}
{#each categoryList as list, index}
  {#if (categoryList.length > 1 || name === 'YouthSection')}
    <h4>{list.category}</h4>
  {/if}
  <ul class='gsheets-data'>
    
  {#each listValues[index] as listValue}
  {#if (combinedAuthorTitle)}
        <li>
          <p>{listValue[1]}</p>
        </li>
  {:else}
    {#if (name === 'RecentDonors')} 
        <li>
          <p>
            {listValue[1]}
            {#if (listValue[2])}
            ({listValue[2]})
            {/if}
          </p>
        </li>
    {:else}
      <li>
        <p>
          {listValue[1]},{' '}
          <span>
            <i>{listValue[2]}</i>
          </span>
        </p>
      </li>
    {/if}
  {/if}
{/each}

  </ul>
  <br />
{/each}
{#if (name === 'Books')}
  <section>
    <b>KAREN MARTORELLI</b><br />
    <i>Acquisitions Chair</i>
  </section>
{/if}

<style>  
  section {
    display: block;
    font-size: 1.2em;
    text-align: left;
	}
  #gsheets-data p {
    font-size: var(--step-1);
    padding-left: 1.5em;
    text-align: left;
    text-indent: -1.5em;
  }

  #updated {
    font-size: 1.2em;
    text-align: right;
    }
</style>
