// src/lib/components/common/menunotphone.jsx

import { pages } from '@/constants';
import { v4 as uuidv4 } from 'uuid';

function MenuSub({ page }) {
  if (!page.subPages) return null;

  return (
    <>
      {page.subPages.map((subPage) => {
        const path = `/${page.path}/${subPage.path}`;
        return (          
            <li key={uuidv4()}>
              <a href={path}>{subPage.name}</a>
            </li>
        );
      })}
    </>
  );
}

function UnorderedList() {
  return (
    <> 
      <ul> 
        {pages.map((page) => {
          const path = `/${page.path}`;
          return (
            <div key={uuidv4()}>
              <li>
                <a href={path}>{page.name}</a>
                <ul>
                  <MenuSub page={page} />
                </ul>
              </li>
            </div>
          );
        })}
      </ul>
    </>
  );
}

export default function MenuNotPhone(){
    return (
        <nav id='menu_not-phone'>
          <a href='#' className='modalClose' hidden></a>
          <div>
            <a href='#' className='modalClose' hidden></a>
            <UnorderedList />
          </div>
        </nav>

    )

}

// src/lib/components/common/menunotphone.svelte
<script>  
  import { pages } from '$lib/constants';
</script>



<nav id='menu_not-phone'>  
  <!-- svelte-ignore a11y-missing-content -->
  <a href='##' class='modalClose' hidden></a>
  <div>
    <!-- svelte-ignore a11y-missing-content -->
    <a href='##' class='modalClose' hidden></a>     
    <ul> 
      {#each pages as page}
          <div>
            <li>
              <a href={page.path !== 'home'? `/${page.path}` : '/'}>{page.name}</a>
              <ul>
                {#if (page.subPages)}
                  {#each page.subPages as subPage}
                    <li>
                      <a href={`/${page.path}/${subPage.path}`}>{subPage.name}</a>
                    </li>
                  {/each}
                {/if}
              </ul>
            </li>
          </div>
      {/each}
    </ul>
  </div>
</nav>
