// src/lib/components/common/navbars/breadcrumbs.jsx
import { Link, useLocation } from 'react-router-dom';
import { pages } from '@/constants';

export default function BreadCrumbs() {
  const { pathname } = useLocation();
  const pathParts = pathname.split('/');
  const path = `/${pathParts[1]}`;
  const page = pages.find((page) => page.path === pathParts[1]);
  const subPages = page.subPages;
  let subPage;
  if (pathParts.length > 2) {
    subPage = subPages.find((subPage) => subPage.path === pathParts[2]);
  }

  return (
    <div className='visibility_phone'>
      {pathParts.length > 2 && (
        <section id='breadcrumbs'>
          <span>
            <Link to={path}>{page.name}</Link>
          </span>
          &nbsp;&raquo;&nbsp;<span>{subPage.name}</span>
        </section>
      )}
    </div>
  );
}

// src/lib/components/common/navbars/breadcrumbs.svelte
<script>
  import { page } from '$app/stores'
  import { pages } from '$lib/constants';
  const pathParts = $page.url.pathname.split('/');
  const path = `/${pathParts[1]}`;
  const mainPage = pages.find((aPage) => aPage.path === pathParts[1]);
  const subPages = mainPage.subPages;
  let subPage;
  if (pathParts.length > 2) {
    subPage = subPages.find((subPage) => subPage.path === pathParts[2]);
  }
</script>

<div class='visbility_phone'>
  {#if (pathParts.length > 2)}
    <section id='breadcrumbs'>
      <span>
        <a href={path}>{mainPage.name}</a>
      </span>
      &nbsp;&raquo;&nbsp;<span>{subPage.name}</span>
    </section>
  {/if}
</div>
