// src/lib/components/common/navbars/navhnotphone.jsx
import { NavLink } from 'react-router-dom';
import { MdMenu as MenuIcon } from 'react-icons/md';
import { pages } from '@/constants';
import { v4 as uuidv4 } from 'uuid';

export default function NavHNotPhone() {
  return (
    <nav className='visibility_not-phone nav_h'>
        <ul > 
          {pages.map((page, index) => {
            const path = `${page.path}`;
            return (
              <li key={uuidv4()}>
                <NavLink
                  to={path}
                  className={({ isActive }) =>
                    isActive ? 'active' : 'inactive'
                  }>
                  {page.name}
                </NavLink>
              </li>
            );
          })}
        <li>
          <a href='#menu_not-phone'><MenuIcon size={25} /></a>
        </li>
      </ul>
    </nav>
  );
}

// src/lib/components/common/navbars/navhnotphone.svelte
<script>
  //import { MdMenu as MenuIcon } from 'react-icons/md';
  import { page } from '$app/stores';
  $: path = $page.url.pathname;
  import { pages } from '$lib/constants';
  import MenuIcon from '$lib/assets/icons/menu.svg'
</script>


<nav class='visibility_not-phone nav_h'>
    <ul > 
      {#each pages as aPage}
          <li>
            <a
              href={aPage.path !== 'home'? `/${aPage.path}` : '/'}
              class={path === '/' ? aPage.path === 'home' ? 'active' : '' : path.includes(aPage.path) ? 'active' : ''}>
              {aPage.name}
            </a>
          </li>
      {/each}
    <li>
      <a href='#menu_not-phone'>
        <img id="menuicon" src={MenuIcon} alt="Menu Icon" /></a>
    </li>
    <li>
      <a href='/menu'>Phone_Menu</a>
    </li>
  </ul>
</nav>
