// src/lib/components/common/navbars/navv.jsx
import { NavLink } from 'react-router-dom';
import { pages } from '@/constants';
import { v4 as uuidv4 } from 'uuid';

export default function NavV({ mainPage }) {
  let path = `/${mainPage.path}`;
  return (
    <nav id='nav_v' className='visibility_not-phone'>
      <ul>
        <li>
          <NavLink
            key={uuidv4()}
            to={path}
            className={({ isActive }) =>
              isActive ? 'active' : 'inactive'
            }
            end>
            {mainPage.name}
          </NavLink>
        </li>
        <li><div className='divider nav-v'></div></li>      
        {mainPage.subPages.map((subPage) => {
          let path = `/${mainPage.path}/${subPage.path}`;
          return (
            <li key={uuidv4()}>
            <NavLink
              to={path}
              className={({ isActive }) =>
                isActive
                  ? 'active'
                  : 'inactive'
              }>
              {subPage.name}
            </NavLink>
            </li>
          );
        })}
      </ul>
    </nav>
  );
}

// src/lib/components/common/navbars/navv.svelte
<script>
  export let mainPage;
  import { page } from '$app/stores';
  let path = `/${mainPage.path}`;
</script>


<nav id='nav_v' class='visibility_not-phone'>
  <ul>
    <li>
      <a
        href={path}
        class={$page.url.pathname === path ? 'active' :  ''}
      >
        {mainPage.name}
      </a>
    </li>
    <li><div class='divider nav-v'></div></li>      
    {#each mainPage.subPages as subPage}
        <li>
        <a
          href={`/${mainPage.path}/${subPage.path}`}
          class={$page.url.pathname === `/${mainPage.path}/${subPage.path}` ? 'active' :  ''}
          >
          {subPage.name}
        </a>
        </li>
      {/each}
  </ul>
</nav>
