// src/routes/(hero)/(sidemenu)/about/artforsale/+page.svelte
<script>  
  import PageBodySideMenu from '$lib/components/common/pagebodysidemenu.svelte';
</script>

<PageBodySideMenu>
  <h2>LOVE ART? LOVE THE VILLAGE LIBRARY?</h2>
  <br />
  <p>
    The next time you come to The Village Library, please take a moment or
    two to view the many wonderful pieces of art that hang in the Ann Resch
    Litten Corridor which leads from the main library into the new addition
    to the library.
  </p>
  <p>
    Many local artists have graciously donated these paintings to The
    Village Library. These artworks are for sale at prices far below their
    intrinsic value. They would be wonderful gifts for a birthday or
    anniversary, or even a wall in your own home.
  </p>
  <p>
    All monies from the sale of these pieces will help The Village Library
    continue its mission to provide you a conveniently located source for
    your reading and listening pleasure.
  </p>
</PageBodySideMenu>

// src/lib/components/about/artforsale.jsx
import { PageBodySideMenu } from '@/components/common';

export default function ArtForSale() {
  return (
    <PageBodySideMenu name={'ArtForSale'}>
      <h2>LOVE ART? LOVE THE VILLAGE LIBRARY?</h2>
      <br />
      <p>
        The next time you come to The Village Library, please take a moment or
        two to view the many wonderful pieces of art that hang in the Ann Resch
        Litten Corridor which leads from the main library into the new addition
        to the library.
      </p>
      <p>
        Many local artists have graciously donated these paintings to The
        Village Library. These artworks are for sale at prices far below their
        intrinsic value. They would be wonderful gifts for a birthday or
        anniversary, or even a wall in your own home.
      </p>
      <p>
        All monies from the sale of these pieces will help The Village Library
        continue its mission to provide you a conveniently located source for
        your reading and listening pleasure.
      </p>
    </PageBodySideMenu>
  );
}
