// src/routes/(hero)/(subpages)/about/board/+page.svelte
<script>
	export let data;
	import PageBody from '$lib/components/pagebody.svelte';
	const organization = data.items.values;
	organization.splice(0, 1);
</script>

<PageBody>
	<p>
		The Village Library, Inc. is a Georgia non-profit [§501 (c) (3)] corporation and is managed by a
		slate of officers elected by a board of directors. The directors are chosen by the members at an
		annual meeting in May of each year.
	</p>
	<h2>Officers & Directors</h2>
	<table id="board">
		<tbody>
			{#each organization as item}
				<tr>
					<td>{item[1]}</td>
					<td>{item[2]}</td>
				</tr>
			{/each}
		</tbody>
	</table>
</PageBody>

<style>
	tr :first-child {
		padding-right: 0.5em;
		text-align: right;
	}
	tr :last-child {
		padding-left: 0.5em;
		text-align: left;
	}
	td {
		font-size: var(--step-1);
		width: 20%;
	}
	table {
		font-family: var(--font-sans-serif);
		margin-left: auto;
		margin-right: auto;
		padding: 0;
		width: 100%;
	}
</style>

// src/lib/components/about/board.jsx
import { useLoaderData } from 'react-router-dom';
import { PageBodySideMenu } from '@/components/common';

export default function Board() {
  const data = useLoaderData();
  const organization = data.values;
  organization.splice(0, 1);

  return (
    <PageBodySideMenu name={'Board'}>
      <p>
        The Village Library, Inc. is a Georgia non-profit [§501 (c) (3)]
        corporation and is managed by a slate of officers elected by a board of
        directors. The directors are chosen by the members at an annual meeting
        in May of each year.
      </p>
      <h2>Officers & Directors</h2>
      <table id='board'>
        <tbody>
          {organization.map((item, index) => (
            <tr key={index}>
              <td>{item[1]}</td>
              <td>{item[2]}</td>
            </tr>
          ))}
        </tbody>
      </table>
    </PageBodySideMenu>
  );
}
