// src/routes/(hero)/(sidemenu)/about/membership/+page.svelte
<script>
  import PageBodySideMenu from '$lib/components/common/pagebodysidemenu.svelte';
</script>

    <PageBodySideMenu>
      <p>
        Membership in The Village Library is open to anyone. It will cost only
        $20 for a family to join. After that, the annual dues are only $20 per
        year per family. This fee will give you full privileges to borrow any of
        our 24,000 books for 3 weeks without charge. You don&apos;t need to be a
        member to purchase any of our thousands of used books.
      </p>
      <p>
        We have a special rate for our latest bestselling books, DVDs and Audio
        Books. We put the latest books and best sellers on &quot;RENTAL&quot;.
        These books are in a special area and will cost $.30 per day. DVDs and
        Audio books, which can be found in the new Ann Resch Litten Memorial
        Wing, will cost $.40 per day. These special charges are imposed to
        encourage people to return these high demand items sooner so that more
        patrons can have access to them. All &quot;Great Courses&quot; CDs and
        DVDs can be checked out the sane as books, free for three weeks.
      </p>
      <p>
        We have no paid employees. The library is managed and staffed by
        volunteers. Volunteers are always needed at the Village Library. If you
        have an interest in helping others, we encourage you to apply to become
        a library volunteer. Some of our volunteers have been active for more
        than 20 years. To be a volunteer, you don’t need library skills, but you
        will need to be able to enter data into a computer. Almost anyone who
        can create email can learn our system.
      </p>
    </PageBodySideMenu>

// src/lib/components/about/membership.jsx
import { PageBodySideMenu } from '@/components/common';

export default function Membership() {
  return (
    <PageBodySideMenu name={'Membership'}>
      <p>
        Membership in The Village Library is open to anyone. It will cost only
        $20 for a family to join. After that, the annual dues are only $20 per
        year per family. This fee will give you full privileges to borrow any of
        our 24,000 books for 3 weeks without charge. You don&apos;t need to be a
        member to purchase any of our thousands of used books.
      </p>
      <p>
        We have a special rate for our latest bestselling books, DVDs and Audio
        Books. We put the latest books and best sellers on &quot;RENTAL&quot;.
        These books are in a special area and will cost $.30 per day. DVDs and
        Audio books, which can be found in the new Ann Resch Litten Memorial
        Wing, will cost $.40 per day. These special charges are imposed to
        encourage people to return these high demand items sooner so that more
        patrons can have access to them. All &quot;Great Courses&quot; CDs and
        DVDs can be checked out the sane as books, free for three weeks.
      </p>
      <p>
        We have no paid employees. The library is managed and staffed by
        volunteers. Volunteers are always needed at the Village Library. If you
        have an interest in helping others, we encourage you to apply to become
        a library volunteer. Some of our volunteers have been active for more
        than 20 years. To be a volunteer, you don’t need library skills, but you
        will need to be able to enter data into a computer. Almost anyone who
        can create email can learn our system.
      </p>
    </PageBodySideMenu>
  );
}
