// src/lib/components/home/upcomingevents.jsx
import { useNavigate } from 'react-router-dom';
import { MdArrowBack as Close } from 'react-icons/md';
import { v4 as uuidv4 } from 'uuid';

export default function UpcomingEvents() {
  const navigate = useNavigate();
  const futureEvents = JSON.parse(localStorage.getItem('futureEvents'));
  const futureEventCount = futureEvents.length;

  const eventsToDisplay = futureEvents.map((event, index) => {
    let imgSource = 'https://drive.google.com/uc?export=view&id=' + event[6];
    return (
      <article key={uuidv4()}>
        <h2>{event[3]}</h2>
        {event[6] && (
          <img className='poster' alt={event[3]} src={imgSource} />
        )}
        <p>
          <b>{event[5]}:</b> {event[2]} -- {event[4]}
        </p>
        {index < futureEventCount - 1 ? (
          <div className='divider side-menu'></div>
        ) : (
          ''
        )}
      </article>
    );
  });

  const EventDisplay = () => <>{eventsToDisplay}</>;  

  function handleClick(event) {
    event.preventDefault();
    navigate(-1);
  }

  return (
    <section id='upcomingeventslist'>
    <button id='close' >
      <Close  size={50} onClick={handleClick} />
    </button>
    <div className='divider full'></div>
      {futureEventCount > 0 ? (
        <EventDisplay key={uuidv4()} />
      ) : (
        <p key={uuidv4()}>There are no upcoming events.</p>
      )}
      <div className='divider full'></div>
    </section>
  );
}

// src/routes/(nohero)/upcomingevents/+page.svelte
<script>
	import { browser } from '$app/environment';
	import { goto } from '$app/navigation';
	let futureEvents;
	let futureEventCount = 0;
	if (browser) {
		futureEvents = JSON.parse(localStorage.getItem('futureEvents'));
		futureEventCount = futureEvents.length;
	}
	import StoryTime from '$lib/assets/images/posters/StoryTime.jpg';
	import BackArrow from '$lib/assets/icons/backarrow.svg';
	const posters = [
		{
			name: 'StoryTime',
			src: StoryTime
		}
	];
	let poster;
	let altText;
	//TODO Where did I get the close icon in tlcgolf-svelte
	//import { MdArrowBack as Close } from 'react-icons/md';

	function handleClick(event) {
		event.preventDefault();
		goto('/');
	}
</script>

<section id="upcomingeventslist">
	<button class="close" on:click={handleClick}>
		<img id="backarrow" src={BackArrow} alt="Back Arrow" />
	</button>
	<br />
	<br />
	<div class="divider full"></div>
	{#if futureEventCount > 0}
		{#each futureEvents as event, index}
			<article>
				<h2>{event[3]}</h2>
				{#if event[6]}
					<img
						class="poster"
						alt={event[3] + ' Poster'}
						src={posters.find((item) => item.name === event[6]).src}
					/>
				{/if}
				<p>
					<b>{event[5]}:</b>
					{event[2]} -- {event[4]}
				</p>
				{#if index < futureEventCount - 1}
					<div class="divider side-menu"></div>
				{/if}
			</article>
		{/each}
	{:else}
		<p>There are no upcoming events.</p>
	{/if}
	<div class="divider full"></div>
</section>

<style>
	#upcomingeventslist {
	margin: 0 auto;
	padding-bottom: 3em;
	white-space: pre-wrap;
	width: var(--page-width);
	}
	#backarrow {
		height: 3em;
	}
</style>
