// src/lib/components/newsevents/newsevents.jsx
import { PageBodySideMenu } from '@/components/common';

export default function NewsEvents() {
  return (
    <PageBodySideMenu name={'NewsEvents'}>
      <h2>
        THE VILLAGE LIBRARY
        <br />
        PRESIDENT&apos;S REPORT
        <br />
        2022-23
      </h2>
      <br />
      <p>
        <b>CHALLENGES & THE MIRACLE</b>
      </p>
      <p>
        The past year began with the annual Board retreat—when we reviewed our
        accomplishments of the prior year and set the priorities for the
        upcoming year. Then we encountered a few speed bumps as we began our
        journey through the year with the departure of people who had occupied
        critical positions: Phil Van Ess departed as Facilities Manager in March
        of 2022; Training Coordinator Liz McAdams moved away in November 2022;
        Treasurer Carol Holland stepped down in early 2023; Book Sale
        Coordinator Kim Hicks moved away after the Fall 2022 book sale;, Youth
        Services Coordinator Kathy Kahn resigned her Board position in Spring
        2023; and IT Consultant Jacob Dimond passed away in December 2022. The
        result was that we spent much of our time and energy this past year
        filling vacancies and training new people.
      </p>
      <p>
        <b>The miracle?</b> The Village Library&apos;s Board and volunteers keep
        the place running through thick and thin. The Village Library exists
        because of the extraordinary effort of over 75 dedicated volunteers who
        devote their time and talents daily. The success of this venture for
        thirty years is the result of dedication and effort of many people who
        carry on in spite of the speed bumps.
      </p>
      <p>
        <b>ACCOMPLISHMENTS</b>
      </p>
      <p>There are accomplishments to highlight this year:</p>
      <section id='accomplishments'>
        <p>
          The Board was successful in its application for a Landlovers&apos; grant
          of $2,100 to fund children&apos;s books and programs and a new printer
          in 2023.
        </p>
        <p>
          Under the leadership of Terry Kessler, the Library successfully
          implemented the Finance Committee&apos;s 2021 recommendation for
          investing the Library’s reserves through a Fidelity brokerage account.
        </p>
        <p>
          Cece Coleman led Collection Development efforts to create a single,
          coordinated approach to the special collections—introducing the Browsing
          Collection with designation of each collection in the catalog. Just Off
          Rental, New, Local Authors, and Recommended books joined the Rental
          books with icons in the online catalog; and the position of Browsing
          Collection Coordinator was created to manage the collections. The result
          is that books in the collection are now easy to find, helping volunteers
          and patrons in their searches.
        </p>
        <p>
          Vice President for Community Relations Brenda Day continued to lead the
          Library&apos;s efforts to expand the Spring and Fall book sales to
          achieve our goal of having a festival of community activities to
          supplement the library&apos;s sidewalk sale. The Landings Art
          Association, the Landings Garden Club, various PEO chapters, and
          individual artists and authors all came together with the library to
          feature their work and sell their wares. Brenda also recruited and
          supported the new Book Sale Coordinator, Lynn Townsend, who successfully
          organized the Spring 2023 sale.
        </p>
        <p>
          Public Information Officer (PIO) Nicole Tifverman set a new, high
          standard for that position—continuing her excellent work publicizing and
          communicating about the Library through social media, work with various
          publications, delightful fliers and img_pictures, and the excellent
          monthly volunteer newsletter. She is leaving her position as PIO but
          will continue as an at-large member of the Board and the new Browsing
          Collection Coordinator.
        </p>
      </section>
      <p>
        I want to highlight the contributions of Vice-President of Operations
        Ren&eacute;e Collins as she departs the Board after three years. Renee’s
        creativity and hard work have led to new procedures, improved customer
        service, and a better Library. She will be missed.
      </p>
      <p>
        There are many other accomplishments to celebrate this year. These are
        just a few examples of the contributions from the Board and volunteers
        this year. Once again this year, I want to emphasize that no President
        succeeds without the work of many, many people—I appreciate each and
        every one of you.
      </p>
      <p>Sandy Cooper, President</p>
      <p>2022-2023</p>
    </PageBodySideMenu>
  );
}

// src/routes/(hero)/(sidemenu)/newsevents/+page.svelte
<script>
  import PageBodySideMenu from '$lib/components/common/pagebodysidemenu.svelte';
</script>
    <PageBodySideMenu>
      <h2>
        THE VILLAGE LIBRARY
        <br />
        PRESIDENT&apos;S REPORT
        <br />
        2022-23
      </h2>
      <br />
      <p>
        <b>CHALLENGES & THE MIRACLE</b>
      </p>
      <p>
        The past year began with the annual Board retreat—when we reviewed our
        accomplishments of the prior year and set the priorities for the
        upcoming year. Then we encountered a few speed bumps as we began our
        journey through the year with the departure of people who had occupied
        critical positions: Phil Van Ess departed as Facilities Manager in March
        of 2022; Training Coordinator Liz McAdams moved away in November 2022;
        Treasurer Carol Holland stepped down in early 2023; Book Sale
        Coordinator Kim Hicks moved away after the Fall 2022 book sale;, Youth
        Services Coordinator Kathy Kahn resigned her Board position in Spring
        2023; and IT Consultant Jacob Dimond passed away in December 2022. The
        result was that we spent much of our time and energy this past year
        filling vacancies and training new people.
      </p>
      <p>
        <b>The miracle?</b> The Village Library&apos;s Board and volunteers keep
        the place running through thick and thin. The Village Library exists
        because of the extraordinary effort of over 75 dedicated volunteers who
        devote their time and talents daily. The success of this venture for
        thirty years is the result of dedication and effort of many people who
        carry on in spite of the speed bumps.
      </p>
      <p>
        <b>ACCOMPLISHMENTS</b>
      </p>
      <p>There are accomplishments to highlight this year:</p>
      <section id='accomplishments'>
        <p>
          The Board was successful in its application for a Landlovers&apos; grant
          of $2,100 to fund children&apos;s books and programs and a new printer
          in 2023.
        </p>
        <p>
          Under the leadership of Terry Kessler, the Library successfully
          implemented the Finance Committee&apos;s 2021 recommendation for
          investing the Library’s reserves through a Fidelity brokerage account.
        </p>
        <p>
          Cece Coleman led Collection Development efforts to create a single,
          coordinated approach to the special collections—introducing the Browsing
          Collection with designation of each collection in the catalog. Just Off
          Rental, New, Local Authors, and Recommended books joined the Rental
          books with icons in the online catalog; and the position of Browsing
          Collection Coordinator was created to manage the collections. The result
          is that books in the collection are now easy to find, helping volunteers
          and patrons in their searches.
        </p>
        <p>
          Vice President for Community Relations Brenda Day continued to lead the
          Library&apos;s efforts to expand the Spring and Fall book sales to
          achieve our goal of having a festival of community activities to
          supplement the library&apos;s sidewalk sale. The Landings Art
          Association, the Landings Garden Club, various PEO chapters, and
          individual artists and authors all came together with the library to
          feature their work and sell their wares. Brenda also recruited and
          supported the new Book Sale Coordinator, Lynn Townsend, who successfully
          organized the Spring 2023 sale.
        </p>
        <p>
          Public Information Officer (PIO) Nicole Tifverman set a new, high
          standard for that position—continuing her excellent work publicizing and
          communicating about the Library through social media, work with various
          publications, delightful fliers and img_pictures, and the excellent
          monthly volunteer newsletter. She is leaving her position as PIO but
          will continue as an at-large member of the Board and the new Browsing
          Collection Coordinator.
        </p>
      </section>
      <p>
        I want to highlight the contributions of Vice-President of Operations
        Ren&eacute;e Collins as she departs the Board after three years. Renee’s
        creativity and hard work have led to new procedures, improved customer
        service, and a better Library. She will be missed.
      </p>
      <p>
        There are many other accomplishments to celebrate this year. These are
        just a few examples of the contributions from the Board and volunteers
        this year. Once again this year, I want to emphasize that no President
        succeeds without the work of many, many people—I appreciate each and
        every one of you.
      </p>
      <p>Sandy Cooper, President</p>
      <p>2022-2023</p>
    </PageBodySideMenu>
