// src/lib/components/about/missionstatement.jsx
import { PageBodySideMenu } from '@/components/common';

export default function MissionStatement() {
  return (
    <PageBodySideMenu name={'MissionStatement'}>
      <p id='mission-statement'>
        The volunteer-run Village Library offers a welcoming environment for
        people of all ages from Skidaway Island and beyond with a collection
        that entertains and enriches.
      </p>
    </PageBodySideMenu>
  );
}

// src/routes/(hero)/(sidemenu)/about/missionstatement/+page.svelte
<script>
  import PageBodySideMenu from '$lib/components/common/pagebodysidemenu.svelte';
</script>

<PageBodySideMenu>
  <p>
    The volunteer-run Village Library offers a welcoming environment for
    people of all ages from Skidaway Island and beyond with a collection
    that entertains and enriches.
  </p>
</PageBodySideMenu>

<style>  
  p {
				border: 2px solid var(--color-secondary);
				border-radius: 20px;
				display: block;
				margin-left: auto;
				margin-right: auto;
				margin-top: 2em;
				padding: 1em;
				width: 80%;
			}
</style>
